<a href="https://colab.research.google.com/github/merdogan97/Statistics/blob/main/Statistics_Assignment_2_19_01_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **## Descriptive Statistics**

# Import **NumPy**, **SciPy**, and **Pandas** 

In [ ]:
import numpy as np
import scipy as sp
import pandas as pd
from scipy import stats

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [ ]:
mu, sigma= 100, 15
samples = np.random.normal(mu, sigma, 1000)
samples

array([ 88.05357695, 116.91766244, 109.24749339, 102.74922219,
       119.75597396, 118.18622004,  95.62258933,  91.43866075,
        93.44307521,  84.94372376,  97.54522921, 103.70747664,
       116.02116948,  91.3734892 , 104.23222409, 108.37221179,
        96.78630258, 115.37864365,  83.87061577,  75.40545614,
       120.25933204,  77.59322985, 122.93025926, 116.69727897,
       117.52373822,  61.74616807,  95.82209419,  99.38473052,
        98.73005694, 124.49809808, 112.91286124,  95.0606817 ,
       102.397083  , 102.51249652, 117.25242992, 105.2677051 ,
       101.82911209, 130.17705854, 128.52917136,  73.49896833,
       104.1034295 , 111.68740897,  96.00058295, 102.91409542,
        96.25847219,  93.40467223,  78.8513827 , 125.6150077 ,
        80.70740805, 108.84180396, 101.67877485,  70.45141708,
        89.29436533,  92.84385515, 106.27244778,  92.4577945 ,
       101.2087359 ,  85.63895817, 121.20271638, 101.45840533,
        94.20691739, 114.07570364,  84.12373606, 115.24

# Compute the **mean**, **median**, and **mode** **kalın metin**

In [ ]:
m = np.mean(samples)
print("Mean: ", m)

Mean:  99.65927433185755


In [ ]:
md = np.median(samples)
print("Median: ", md)

Median:  99.50819167143791


In [ ]:
stats.mode(samples)

ModeResult(mode=array([45.55046792]), count=array([1]))

# Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range** 

In [ ]:
min = np.min(samples)
print("min: ", min)

min:  45.55046792098858


In [ ]:
max = np.max(samples)
print("max: ", max)

max:  143.55164499488308


In [ ]:
q1= np.percentile(samples, 25)
print("Q1: ", q1)

Q1:  90.49955915971123


In [ ]:
q3 = np.percentile(samples, 75)
print("Q3: ", q3)

Q3:  109.48514899681822


In [ ]:
iqr= stats.iqr(samples)
print("IQR: ", iqr)

IQR:  18.985589837107


# Compute the **variance** and **standard deviation** **kalın metin**

In [ ]:
variance = np.var(samples)
print("variance: ", variance)


variance:  218.16565998895734


In [ ]:
std = np.std(samples)
print("Standard_Deviation: ", std)

Standard_Deviation:  14.770431949978896


# Compute the **skewness** and **kurtosis** 

In [ ]:
skw = stats.skew(samples)
print("Skewness: ", skw)

Skewness:  -0.05499333000904295


In [ ]:
krt= stats.kurtosis(samples)
print("Kurtosis: ", krt)

Kurtosis:  -0.144844942938835


# **NumPy Correlation Calculation**

# **Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`**

In [ ]:
x = np.arange(10,20)
print(x)

[10 11 12 13 14 15 16 17 18 19]


# **Then use `np.array()` to create a second array y containing 10 arbitrary integers.**

In [ ]:
y = np.array([1,2,3,4,5,6,7,8,9,10])
print(y)

[ 1  2  3  4  5  6  7  8  9 10]


# Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y **kalın metin**

In [ ]:
x = np.array([1,2,3])
print(x)

[1 2 3]


In [ ]:
y = np.array([4,5,6])
print(y)

[4 5 6]


In [ ]:
cor= np.corrcoef(x,y)
print(cor)

[[1. 1.]
 [1. 1.]]


In [ ]:
co= np.correlate(x,y)
print(co)

[32]


# **Pandas Correlation Calculation**

Run the code below

In [ ]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [ ]:
r = stats.pearsonr(x, y)
print("Pearson's r Corerelation: ", r)

Pearson's r Corerelation:  (0.758640289091187, 0.010964341301680813)


OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [ ]:
rho, pval = stats.spearmanr(x, y)
rho

0.9757575757575757

In [ ]:
rho, pval = stats.spearmanr(x, y)
pval

1.4675461874042197e-06

## **Seaborn Dataset Tips**

# Import Seaborn Library

In [ ]:
import seaborn as sns

# Load "tips" dataset from Seaborn

In [ ]:
tips = sns.load_dataset("tips")
print(tips)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]


# **Generate descriptive statistics include those that summarize the central tendency, dispersion**

In [ ]:
total_bill = tips["total_bill"].values
print(total_bill)

[16.99 10.34 21.01 23.68 24.59 25.29  8.77 26.88 15.04 14.78 10.27 35.26
 15.42 18.43 14.83 21.58 10.33 16.29 16.97 20.65 17.92 20.29 15.77 39.42
 19.82 17.81 13.37 12.69 21.7  19.65  9.55 18.35 15.06 20.69 17.78 24.06
 16.31 16.93 18.69 31.27 16.04 17.46 13.94  9.68 30.4  18.29 22.23 32.4
 28.55 18.04 12.54 10.29 34.81  9.94 25.56 19.49 38.01 26.41 11.24 48.27
 20.29 13.81 11.02 18.29 17.59 20.08 16.45  3.07 20.23 15.01 12.02 17.07
 26.86 25.28 14.73 10.51 17.92 27.2  22.76 17.29 19.44 16.66 10.07 32.68
 15.98 34.83 13.03 18.28 24.71 21.16 28.97 22.49  5.75 16.32 22.75 40.17
 27.28 12.03 21.01 12.46 11.35 15.38 44.3  22.42 20.92 15.36 20.49 25.21
 18.24 14.31 14.    7.25 38.07 23.95 25.71 17.31 29.93 10.65 12.43 24.08
 11.69 13.42 14.26 15.95 12.48 29.8   8.52 14.52 11.38 22.82 19.08 20.27
 11.17 12.26 18.26  8.51 10.33 14.15 16.   13.16 17.47 34.3  41.19 27.05
 16.43  8.35 18.64 11.87  9.78  7.51 14.07 13.13 17.26 24.55 19.77 29.85
 48.17 25.   13.39 16.49 21.5  12.66 16.21 13.81 17.

In [ ]:
m = np.mean(total_bill)
print("Mean: ", m)

Mean:  19.78594262295082


In [ ]:
md = np.median(total_bill)
print("Median: ", md)

Median:  17.795


In [ ]:
stats.mode(total_bill)

ModeResult(mode=array([13.42]), count=array([3]))

In [ ]:
variance = np.var(total_bill)
print("variance: ", variance)


variance:  78.92813148851114


In [ ]:
std = np.std(total_bill)
print("Standard_Deviation: ", std)

Standard_Deviation:  8.884150577771132


# **Call the relevant method to calculate pairwise Pearson's r correlation of columns**

In [ ]:
tip = tips["tip"].values
print(t)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

In [ ]:
r, p = stats.pearsonr(total_bill,tip)
r

0.6757341092113647